image: rust

services:
  - postgres:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update
  - apt install -y postgresql-client
  - sh ./dbscripts/setup.sh
  - cd .. 
  - git clone https://github.com/ivanceras/sqlite
  - git clone https://github.com/ivanceras/r2d2-sqlite3
  - git clone https://github.com/ivanceras/bazaar
  - git clone https://github.com/ivanceras/dota-sql
  - cd bazaar/scripts && sh setup.sh && cd .. && cd ..
  - cd dota-sql/data && sh reimport.sh && cd .. && cd ..
  - find . -name '*.rs' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - find . -name '*.sh' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - cd diwata
  - rustup override set nightly

stages:
  - build
  - test

test:
  script:
    - cargo test --all-features

build:
  script:
    - cargo build -p diwata --release
