stages:
  - build


rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  services:
      - postgres:latest
  variables:
     GIT_SUBMODULE_STRATEGY: recursive

  before_script:
      - cd crates/rustorm
      - ./install-postgresql-client.sh
      - ./rename-database-host.sh
      - ./execute-data-import.sh
      - cd -

  script:
      - cargo test --all
