image: rust

services:
  - postgres:latest

variables:
  POSTGRES_DB: db1
  POSTGRES_USER: postgres 
  POSTGRES_PASSWORD: p0stgr3s
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - apt update
  - apt install -y postgresql-client
  - psql -U $POSTGRES_USER -h postgres -c 'CREATE DATABASE sakila;' 
  - psql -U $POSTGRES_USER -h postgres -d $POSTGRES_DB -f ./sakila/postgres-sakila-db/postgres-sakila-schema.sql 
  - psql -U $POSTGRES_USER -h postgres -d $POSTGRES_DB -f ./sakila/postgres-sakila-db/postgres-sakila-data.sql
  - psql -U $POSTGRES_USER -h postgres -c "ALTER USER postgres WITH PASSWORD 'p0stgr3s';"
  - echo `pwd` && ls -la
  - cd .. && git clone https://github.com/ivanceras/sqlite
  - git clone https://github.com/ivanceras/r2d2-sqlite3
  - cd curtain-rewrite
  - find . -name '*.rs' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - rustup override set nightly

stages:
  - build
  - test

test:
  script:
    - cargo test --all-features

build:
  script:
    - cargo build -p webserver --release
