image: rustlang/rust:nightly

services:
  - postgres:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - cd .. && git clone https://github.com/ivanceras/bazaar && cd -
  - cd .. && git clone https://github.com/ivanceras/dota-sql && cd -
  - apt update
  - apt install -y postgresql-client
  - find . -name '*.sh' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - sh ./dbscripts/setup.sh
  - pwd && ls -la
  - cd .. 
  - find . -name '*.sh' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - cd  bazaar/scripts && sh setup.sh
  - pwd && ls -la
  - cd .. && cd ..
  - cd dota-sql/data && sh reimport.sh
  - pwd && ls -la
  - cd .. && cd ..
  - cd diwata
  - find . -name '*.rs' -type f -exec sed -i 's/localhost/postgres/g' {} +

stages:
  - build
  - test

test:
  script:
    - cd rustorm && sh ./test.sh && cd -
    - cargo test --all --all-features
    - cargo test -p rustorm --all-features
    - cargo test -p rustorm --features "with-postgres with-sqlite"
    - cargo test -p rustorm --features "with-postgres"
    - cargo test -p rustorm --features "with-sqlite"

build:
  script:
    - cargo build -p diwata_server --release
