stages:
  - build


rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  services:
      - postgres:latest

  before_script:
      - cd rustorm 
      - ./install-postgresql-client.sh
      - ./rename-database-host.sh
      - ./execute-data-import.sh
      - cd -

  script:
      - cargo test --all
