image: rust

services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres 
  POSTGRES_USER: postgres 
  POSTGRES_PASSWORD: p0stgr3s
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - find . -name '*.sh' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - sh ./dbscripts/setup.sh
  - pwd && ls -la
  - cd .. 
  - git clone https://github.com/ivanceras/sqlite
  - git clone https://github.com/ivanceras/r2d2-sqlite3
  - git clone https://github.com/ivanceras/bazaar
  - find . -name '*.sh' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - cd  bazaar/scripts && sh setup.sh
  - pwd && ls -la
  - cd .. && cd ..
  - cd curtain-rewrite
  - find . -name '*.rs' -type f -exec sed -i 's/localhost/postgres/g' {} +
  - rustup override set nightly

stages:
  - build
  - test

test:
  script:
    - cargo test --all-features

build:
  script:
    - cargo build -p webserver --release
