os:
  - linux

language: rust

rust:
  - nightly

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - git clone https://github.com/ivanceras/bazaar
  - git clone https://github.com/ivanceras/sakila
  - git clone https://github.com/ivanceras/dota-sql
  - pwd
  - ls -la
  - sh ./dbscripts/setup.sh
  - cd ../dota-sql/data/ && sh reimport.sh && cd -
  - cd ../bazaar/scripts && sh setup.sh && cd -
  - cd ../dota-sql/data && sh reimport.sh && cd -
  - pwd
  - mkdir -p public/static
  - cd intel && cargo update && cd -
  - pwd
  - cd server && cargo update && cd -
  - pwd


  
script:
  - cargo update
  - cargo build -p diwata_server --release
  - cargo test --all-features
  - cd rustorm && sh ./test.sh && cd -
