os:
  - linux

language: rust

rust:
  - stable
  - nightly

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - rustup component add clippy
  - cd crates/rustorm
  - ./execute-data-import.sh
  - cd -


  
script:
  - cargo test -p rustorm --all-features
  - cargo test -p diwata_intel
  - cargo test -p dataview
  - cargo clippy
