os:
  - linux

language: rust

rust:
  - nightly

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - pwd
  - ls -la
  - cd .. && git clone https://github.com/ivanceras/bazaar && cd -
  - cd .. && git clone https://github.com/ivanceras/dota-sql && cd -
  - pwd
  - ls -la
  - sh ./dbscripts/setup.sh
  - cd ../dota-sql/data/ && sh reimport.sh && cd -
  - cd ../bazaar/scripts && sh setup.sh && cd -
  - cd ../dota-sql/data && sh reimport.sh && cd -
  - pwd
  - mkdir -p public/static
  - cd intel && cargo update && cd -
  - pwd
  - cd server && cargo update && cd -
  - pwd


  
script:
  - cargo update
  - cargo build -p diwata_server --release
  - cargo test --all
  - cargo test --all --all-features
  - cargo test -p rustorm --all-features
  - cargo test -p rustorm --features "with-postgres with-sqlite"
  - cargo test -p rustorm --features "with-postgres"
  - cargo test -p rustorm --features "with-sqlite"
