os:
  - linux

language: rust

rust:
  - nightly

services:
  - postgresql

before_script:
  - psql -U postgres -h localhost -c 'CREATE DATABASE sakila;' 
  - psql -U postgres -h localhost -d sakila -f ./sakila/postgres-sakila-db/postgres-sakila-schema.sql 
  - psql -U postgres -h localhost -d sakila -f ./sakila/postgres-sakila-db/postgres-sakila-data.sql
  - psql -U postgres -h localhost -d sakila -f ./composite_foreign_key.sql
  - psql -U postgres -h localhost -d sakila -f ./add_users.sql
  - psql -U postgres -h localhost -c "ALTER USER postgres WITH PASSWORD 'p0stgr3s';"
  - cd /home/travis/build/copyleft && git clone https://github.com/ivanceras/sqlite
  - cd /home/travis/build/copyleft && git clone https://github.com/ivanceras/r2d2-sqlite3
  - cd /home/travis/build/copyleft/curtain

  
script:
  - cargo test --all-features
