os:
  - linux

language: rust

rust:
    #- stable
  - nightly

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - cd crates/rustorm
  - ./execute-data-import.sh
  - cd -
  - cd ../ && git clone https://github.com/ivanceras/sauron
  - cd -
  - cd ../ && git clone https://github.com/ivanceras/sqlparser-rs
  - cd -



script:
  - cargo test --all
