os:
  - linux

language: rust

rust:
  - nightly

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE sakila;' -U postgres
  - psql -U postgres -h localhost -d sakila -f ./sakila/postgres-sakila-db/postgres-sakila-schema.sql 
  - psql -U postgres -h localhost -d sakila -f ./sakila/postgres-sakila-db/postgres-sakila-data.sql
  - cd .. && git clone https://github.com/ivanceras/sqlite
  - git clone https://github.com/ivanceras/r2d2-sqlite3
  - echo `pwd` && ls -la

  
script:
  - cargo test --all-features
