os:
  - linux

language: rust

rust:
  - nightly

services:
  - postgresql

before_script:
  - dbscripts/setup.sh
  - cd ..
  - git clone https://github.com/ivanceras/sqlite
  - git clone https://github.com/ivanceras/r2d2-sqlite3
  - git clone https://github.com/ivanceras/bazaar
  - cd bazaar/scripts && sh setup.sh
  - cd .. && cd ..
  - cd curtain

  
script:
  - cargo test --all-features
