[workspace]
members = [
    "intel",
    "server",
    "rustorm",
    "rustorm/crates/codegen",
    "rustorm/crates/dao",
    "witch-client",
    "witch-client/witch",
    "text-client",
]

[replace]
"rustorm_dao:0.2.0" = { path = "rustorm/crates/dao" }
"rustorm_codegen:0.2.0" = { path = "rustorm/crates/codegen" }
"rustorm:0.11.0" = { path = "rustorm" }
"diwata_intel:0.1.2" = { path = "intel" }
