[workspace]
members = [
    "crates/rustorm",
    "crates/rustorm/crates/dao",
    "crates/rustorm/crates/codegen",
    "crates/intel",
    "crates/server",
    "crates/text-client",
]

exclude = [
    "crates/webclient",
]

[replace]
"rustorm_dao:0.2.0" = { path = "crates/rustorm/crates/dao" }
"rustorm_codegen:0.2.0" = { path = "crates/rustorm/crates/codegen" }
"rustorm:0.11.0" = { path = "crates/rustorm" }
"diwata_intel:0.1.2" = { path = "crates/intel" }
