[workspace]
members = [
    "intel",
    "diwata",
    "rustorm",
    "rustorm/codegen",
    "rustorm/dao"
]

[replace]
#"rustorm_dao:0.1.0" = { path = "rustorm/dao" }
#"rustorm_codegen:0.1.1" = { path = "rustorm/codegen" }
#"rustorm:0.10.1" = { path = "rustorm" }
