[workspace]
members = [
    "intel",
    "server",
    "rustorm",
    "rustorm/codegen",
    "rustorm/dao",
    "cli"
]

#[replace]
#"rustorm_dao:0.1.1" = { path = "rustorm/dao" }
#"rustorm_codegen:0.1.2" = { path = "rustorm/codegen" }
#"rustorm:0.10.1" = { path = "rustorm" }
