[workspace]
members = [
    "crates/rustorm",
    "crates/rustorm/crates/dao",
    "crates/rustorm/crates/codegen",
    "crates/intel",
    "crates/server",
    "crates/text-client",
    "crates/dataview",
    "crates/webclient",
]

[replace]
"rustorm_dao:0.3.0" = { path = "crates/rustorm/crates/dao" }
"rustorm_codegen:0.3.0" = { path = "crates/rustorm/crates/codegen" }
"rustorm:0.13.0" = { path = "crates/rustorm" }
"diwata_intel:0.1.2" = { path = "crates/intel" }
"sauron:0.4.0" = { path = "../sauron" }
"sauron_vdom:0.4.0"= { path = "../sauron/crates/sauron_vdom" }

