[package]
name = "dao"
version = "0.1.0"
authors = ["lee"]
description = "Dao provides a flexible way to access data from the database"

[dependencies]
chrono = "0.4.0"
uuid = {version = "0.5.1", features = ["v4"]}
