[package]
name = "witch-client"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.4.0"
witch = { path = "witch" }
sqlparser = "0.1.8"
rustorm = {path = "../rustorm"}
csv = "1.0.2"
stdweb = "0.4.10"
