[package]
name = "intel"
version = "0.1.0"
authors = ["lee"]

[dependencies]
rustorm = {path = "../rustorm"}
rustorm_codegen = {path = "../rustorm/codegen"}
dao = {path = "../rustorm/dao"}
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
lazy_static = "1.0.0"
uuid = "0.5.1"
bigdecimal = "0.0.10"
clippy = { version = "*", optional = true }
