[package]
name = "data_table"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"

[dependencies]
sqlparser = { path = "../sqlparser-rs" }
csv = "1.0.2"
rustorm = "0.14.0"
diwata_intel = "0.1.2"
