[package]
name = "webserver"
version = "0.1.0"
authors = ["lee"]

[dependencies]
rustorm = { path = "../rustorm" }
chrono = "0.4.0"
dao = {path = "../rustorm/dao"}
rustorm_codegen = {path = "../rustorm/codegen"}

